### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by kou** [kenhys/sphinxcontrib-openstreetmap#1]
I can't find sphinxcontrib-openstreetmap at PyPI: http://pypi.python.org/pypi/sphinxcontrib-openstreetmap

**Comment by kenhys** [comment]
I had never published it at PyPI, so it is correct that it returns 404 when you access to http://pypi.python.org/pypi/sphinxcontrib-openstreetmap.

Anyway, I've just uploaded it, so after a while, sphinxcontrib-openstreetmap will be available.

```
% pip search sphinxcontrib G open
sphinxcontrib-docbookrestapi (0.2.1)           - Extension to Sphinx for generating REST API documentation for http://api.openstack.org/
```

sphinxcontrib-openstreetmap is not listed yet. (2016/3/31 0:00 JST)

**Comment by kou** [comment]
Thanks.
